### PR TITLE
Add function to filter on accept header

### PR DESCRIPTION
**Pull request by pheyvaer**
@rubensworks Can you have a look at the content types and see if I missed anything? Thanks!

### CODE REVIEW

**Comment by rubensworks** [comment]
Here's a table of all content types comunica could request: https://github.com/rubensworks/rdf-parse.js?tab=readme-ov-file#rdf-parse
Maybe we can add all of them.

So if I understand correctly, this will still work for complex accept headers with q-values?

**Comment by pheyvaer** [comment]
I added the missing content types.

Yes, the q-values are ignored when checking the content types.
One thing that is important: the moment `*/*` is part of the header the proxy will say it's invalid. It requires that all content types in the header are in the list that we provide.

**Comment by rubensworks** [comment]
> One thing that is important: the moment */* is part of the header the proxy will say it's invalid. It requires that all content types in the header are in the list that we provide.

This may be a problem, since Comunica when run in the browser can not send it's full Accept header (because of CORS, again 😠), so it splices of some content-types and replaces it with */*.

**Comment by pheyvaer** [comment]
What we can do is say that `*/*` can be included if at least one other type is added and that all other types are from our list. Would that fix it for you/Comunica?

**Comment by rubensworks** [comment]
> What we can do is say that */* can be included if at least one other type is added and that all other types are from our list. Would that fix it for you/Comunica?

Yes, I think that could work!

**Comment by pheyvaer** [comment]
I changed it.

**Comment by rubensworks** [comment]
Thanks!

**Pull request merged**
